apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep-1
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - image:  nginx
          name:  nginx
