apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-nginx
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx

